# Generated by Django 5.0.7 on 2024-07-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('userInventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('userInventoryName', models.CharField(max_length=255)),
                ('userInventoryState', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='server.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('subProductId', models.AutoField(primary_key=True, serialize=False)),
                ('subProductName', models.CharField(max_length=255)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='server.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SelectData',
            fields=[
                ('selectDataId', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ManyToManyField(related_name='selectdata', to='server.product')),
                ('subCategory', models.ManyToManyField(related_name='selectdata', to='server.subcategory')),
                ('subProducts', models.ManyToManyField(related_name='selectdata', to='server.subproduct')),
            ],
        ),
    ]
