# Generated by Django 5.0.7 on 2024-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_zohotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohotoken',
            name='api_domain',
            field=models.URLField(default='https://www.zohoapis.eu'),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='scope',
            field=models.CharField(default='ZohoCRM.modules.ALL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=50),
            preserve_default=False,
        ),
    ]
