# Generated by Django 5.0.7 on 2024-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_zohotoken_api_domain_zohotoken_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('lead_status', models.CharField(max_length=255)),
                ('zoho_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zohotoken',
            name='api_domain',
            field=models.URLField(),
        ),
    ]
