# Generated by Django 5.0.7 on 2024-07-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_lead_alter_zohotoken_api_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='lead_status',
            new_name='status',
        ),
    ]
